const IS_LOADING_SIGN_IN = "IS_LOADING_SIGN_IN";
const LOADED_SIGN_IN = "LOADED_SIGN_IN";
const SUCCESSFUL_SIGN_IN = "SUCCESSFUL_SIGN_IN";

const IS_LOADING_SIGN_UP = "IS_LOADING_SIGN_UP";
const LOADED_SIGN_UP = "LOADED_SIGN_UP";
const SUCCESSFUL_SIGN_UP = "SUCCESSFUL_SIGN_UP";

const authConstants = {
  IS_LOADING_SIGN_IN,
  LOADED_SIGN_IN,
  SUCCESSFUL_SIGN_IN,
  IS_LOADING_SIGN_UP,
  LOADED_SIGN_UP,
  SUCCESSFUL_SIGN_UP,
}

export default authConstants;