const GET_ALL_POSTS = "GET_ALL_POSTS";
const GET_ONE_POST = "GET_ONE_POST";
const CREATE_ONE_POST = "CREATE_ONE_POST";
const UPDATE_ONE_POST = "UPDATE_ONE_POST";
const DELETE_ONE_POST = "DELETE_ONE_POST";
const IS_LOADING_POST = "LOADING_POST";
const LOADED_POST = "LOADED_POST";
const HAS_ERROR_POST = "HAS_ERROR_POST";
const HAS_MESSAGE_POST = "HAS_MESSAGE_POST";

const postConstants = {
  GET_ALL_POSTS,
  GET_ONE_POST,
  CREATE_ONE_POST,
  UPDATE_ONE_POST,
  DELETE_ONE_POST,
  IS_LOADING_POST,
  LOADED_POST,
  HAS_ERROR_POST,
  HAS_MESSAGE_POST,
};

export default postConstants;
