const GET_ALL_TAGS = "GET_ALL_TAGS";
const GET_ONE_TAG = "GET_ONE_TAG";
const CREATE_ONE_TAG = "CREATE_ONE_TAG";
const UPDATE_ONE_TAG = "UPDATE_ONE_TAG";
const DELETE_ONE_TAG = "DELETE_ONE_TAG";
const IS_LOADING_TAG = "LOADING_TAG";
const LOADED_TAG = "LOADED_TAG";
const HAS_ERROR_TAG = "HAS_ERROR_TAG";
const REMOVE_ERROR_TAG = "REMOVE_ERROR_TAG";

const tagConstants = {
  GET_ALL_TAGS,
  GET_ONE_TAG,
  CREATE_ONE_TAG,
  UPDATE_ONE_TAG,
  DELETE_ONE_TAG,
  IS_LOADING_TAG,
  LOADED_TAG,
  HAS_ERROR_TAG,
  REMOVE_ERROR_TAG,
};
